[project]
name = "finance-bot"
version = "0.1.0"
description = "A personal finance chatbot using FastAPI and OpenAI to answer financial questions in an educational and accessible way"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "uvicorn>=0.34.0",
]
